version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    ports:
      - '3001:3001'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'